### ISSUE TITLE
Request for next PyPi version push

### ISSUE THREAD

**Issue by janblumenkamp** [naver/roma#13]
Thanks for creating this great library!
I see that there was a fix for an issue I encountered today three weeks ago in commit 40a0a9f21. Unfortunately, the most recent version on PyPi is 1.4.1, which is from early October. For now I can hotfix this, but when is planned to release this to PyPi?

**Comment by rbregier** [comment]
Hi, thanks for the kind words. RoMa v1.4.2 should now be available using PIP.
Let me know if you face any issues.
