### ISSUE TITLE
quat_composition does not normalise

### ISSUE THREAD

**Issue by jamiesalter** [naver/roma#14]
I was just looking through the code and it seems [quat_composition ](https://github.com/naver/roma/blob/37b2c50b90e2ec0f2ce7f9e9ed808e9deabf30a3/roma/utils.py#L223)does not normalise the result.  See code below, it looks like `res` is not normalised.
```
    assert len(sequence) > 1, "Requiring at least two inputs."
    res = sequence[0]
    for q in sequence[1:]:
        res = quat_product(res, q)
    if normalize:
        q = q / torch.norm(q, dim=-1, keepdim=True)
    return res
```

**Comment by rbregier** [comment]
Hi, indeed thank you for the bug report. I should push a fix next week.

**Comment by rbregier** [comment]
v1.4.3 solves this issue. Thanks for the feedback!
