### ISSUE TITLE
License of RoMa (BSD or Creative commons NonCommercial ShareAlike) ?

### ISSUE THREAD

**Issue by jmargeta** [naver/roma#17]
Hi, thanks for this nice lib. What is the license of RoMA, please?

The [license file](https://github.com/naver/roma/blob/master/LICENSE) looks like a 3-clause BSD, however, the current [docs](https://github.com/naver/roma/blob/master/docsource/source/index.rst) claim:  "RoMa, Copyright (c) 2021 NAVER Corp., is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 license (see [license](https://github.com/naver/roma/blob/master/LICENSE))."

**Comment by rbregier** [comment]
Hi,
Good catch, I forgot to update the documentation.
RoMa uses a BSD license.

Fixed in 11e26b9ca6e39acf0d8952f714225800b6da192b
I should update the online doc soon with the release of v1.5.0
