### ISSUE TITLE
missing git tags for releases

### ISSUE THREAD

**Issue by nim65s** [naver/roma#19]
Hello,

This repository has a git tag for v1.2.1, but not for other versions. Could those be added, at least for the last one ?

Context: I'm trying to add this package in [nixpkgs](https://github.com/NixOS/nixpkgs/)

Thanks !

**Comment by rbregier** [comment]
Hi,
Thanks for your interest. I am not familiar with nixpkgs, but I can add tags for the current and future releases.
How should be formatted the versioning tags? "v1.5.1" for example?

**Comment by rbregier** [comment]
I just pushed the "v1.5.1" tag, feel free to close the issue if that is ok for you, and thanks for the feedback.

**Comment by nim65s** [comment]
Perfect, it works for me, thanks a lot !
