### ISSUE TITLE
Variable name error in `roma/mappings.py`

### ISSUE THREAD

**Issue by NatureGeorge** [naver/roma#5]
Something wrong in line 27 of `roma/mappings.py`.

https://github.com/naver/roma/blob/fa66d5a9095d330b297905ec67ed273601184792/roma/mappings.py#L13-L27

https://github.com/naver/roma/blob/fa66d5a9095d330b297905ec67ed273601184792/roma/mappings.py#L27

It should be `SVt = SVt.clone()`?

**Comment by rbregier** [comment]
Hi, thank you very much for reviewing the code.
Indeed, this is wrong. It seems that it did not have any negative impact however: this line was never reached during execution, according to some quick tests.

Fixed in a2ecaafd7dc6f8b794b2e60dc1324e5c1bcd10c9
