### ISSUE TITLE
Error with CUDA

### ISSUE THREAD

**Issue by duytrangiale** [naver/roma#7]
Dear author,

Recently I used your library to convert between rotvec and rotmat. My calculation consists of different equations. I came up with a strange error like this:

R_n1_n = torch.matmul(R_n1, torch.inverse(R_n))
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Do you have any suggestion for this error? Thanks for your help.
Duy

**Comment by duytrangiale** [comment]
I only use two functions rotvec_to_rotmat and rotmat_to_rotvec in my code, could you please have a look to see if there is any potential issue from these functions?

**Comment by duytrangiale** [comment]
Hi Bregier,

I just realise the code works perfectly fine on CPU. So I think there is something wrong with my GPU config.

**Comment by duytrangiale** [comment]
After running for more than 20000 iterations, the neural network outputs become NaN values, do you have any idea to solve this problem?
My learning rate is 5e-4 and batch size is 16

**Comment by rbregier** [comment]
With so little information it's hard to tell.
I will close the issue as it does not seem related to RoMa.
