### ISSUE TITLE
rotmat_to_rotvec directly conversion

### ISSUE THREAD

**Issue by duytrangiale** [naver/roma#8]
Hi,

I just wonder is there anyway that we can convert rotation matrices to rotation vectors directly without converting to quaternions in the middle as we are doing now. I have issue with backpropagation with this function.

Thanks for your help.

**Comment by duytrangiale** [comment]
Hi,

Do you have any test case for rotvec_to_rotmat() function when backpropagation, I get stuck when doing that at the point:
 yzc = ky*kz*one_minus_cos_theta
File "/apps/pytorch/1.9.0-py39-cuda112/lib/python3.9/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/apps/pytorch/1.9.0-py39-cuda112/lib/python3.9/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.

Although the value of one_minus_cos_theta looks fine (no NaN value) but somehow it has issue when computing gradient

**Comment by rbregier** [comment]
Hi,
Do you have a minimal (non) working example of your issue?
There are cases were the gradient is fundamentally undefined, e.g. when considering a rotation close to 180°.

**Comment by duytrangiale** [comment]
Hi,

Unfortunately I don't have a minimal version for my issue. But I can describe for you to run a test case for me.

Let say I have inputs are tensors: r_n, delta_r of size (N,3). The delta_r is output of network, can be arbitrary value. I want to rotate r_n with delta_r so I convert them to rotation matrix using rotvec_to_rotmat().
`R_n = rotvec_to_rotmat(r_n)`
`delta_R = rotvec_to_rotmat(delta_r)`
`R_n1 = torch.matmul(delta_R, R_n)`

Finally convert R_n1 back to rotation vector
`r_n1 = rotmat_to_rotvec(R_n1)`

Currently, I got this error:
r_n1 = rotmat_to_rotvec(R_n1)
  File "/home/le055/.local/lib/python3.9/site-packages/roma/mappings.py", line 411, in rotmat_to_rotvec
    return unitquat_to_rotvec(q)
  File "/home/le055/.local/lib/python3.9/site-packages/roma/mappings.py", line 258, in unitquat_to_rotvec
    scale[large_angle] = (angle[large_angle] / torch.sin(half_angle[large_angle]))

**Comment by rbregier** [comment]
You forgot to paste the actual error you get.
If you could produce a minimal example where the error occurs I could have a look. Otherwise it is rather hard to tell.

Regardless, for such use case you might want to directly use something like this instead (I did not check the exact syntax):
```bash
r_n1 = roma.rotvec_composition([delta_r, r_n], normalize=True)
```

**Comment by duytrangiale** [comment]
Hi,
So the error that I got is something like this (I extract the part that show where the error occurs):

**r_n1 = rotmat_to_rotvec(R_n1)**
  File "/home/le055/.local/lib/python3.9/site-packages/roma/mappings.py", line 411, in rotmat_to_rotvec
    return unitquat_to_rotvec(q)
  File "/home/le055/.local/lib/python3.9/site-packages/roma/mappings.py", line 258, in unitquat_to_rotvec
    **scale[large_angle] = (angle[large_angle] / torch.sin(half_angle[large_angle]))**
    
   total_loss.backward()
  File "/apps/pytorch/1.9.0-py39-cuda112/lib/python3.9/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/apps/pytorch/1.9.0-py39-cuda112/lib/python3.9/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
**RuntimeError: merge_sort: failed on 2nd step: cudaErrorIllegalAddress: an illegal memory access was encountered**

**Comment by duytrangiale** [comment]
This time, I don't convert from rotvec to rotmat anymore. I use rotvec_composition to directly update the vector, but still have error in backward pass:

**r_n1 = rotvec_composition([delta_r, r_n_star], normalize=True)**
  File "/home/le055/.local/lib/python3.9/site-packages/roma/utils.py", line 270, in rotvec_composition
    return **roma.unitquat_to_rotvec(q)**
  File "/home/le055/.local/lib/python3.9/site-packages/roma/mappings.py", line 280, in unitquat_to_rotvec
    **torch.sin(half_angle[large_angle]))**
 (function _print_stack)
 
 total_loss.backward()
  File "/apps/pytorch/1.9.0-py39-cuda112/lib/python3.9/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/apps/pytorch/1.9.0-py39-cuda112/lib/python3.9/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
**RuntimeError: merge_sort: failed on 2nd step: cudaErrorIllegalAddress: an illegal memory access was encountered**

I will try to create a minimal example to test but not too sure about that

**Comment by duytrangiale** [comment]
Hi,

I just realise that when I replace **delta_r** (rotation vectors produced by the network) with a ground truth vector, the code can run without issue. Can you think of any case of **delta_r** that make the code broken so I can find a way to constrain this output of network?

**Comment by duytrangiale** [comment]
Hi,

The reason why it doesn't work with **delta_r** (the output of network) but work with another input vector is that the delta_r has `requires_grad=True` whereas the other vector that I test has `requires_grad=False`. The issue doesn't come from the actual value of it.

Could you help me check this issue.

**Comment by duytrangiale** [comment]
Hi,

I have updated to pytorch 1.12 and avoid using rotvec_to_rotmat() function (there is error of backward pass if I use it) and it runs now.

**Comment by rbregier** [comment]
Hi,
Could you please provide a complete python example where the backward error occurs with `rotvec_to_rotmat`?

**Comment by duytrangiale** [comment]
Hi,

I will try to make a simple case where the error occurs but not sure if I can do that.

**Comment by duytrangiale** [comment]
Hi,
I have tried to make a simpler example to replicate the error that I got but I can't. It may just come from my particular case so I think in general, there is no issue with the library itself. I also run a simple training code using rotvec_to_rotmat() and it works fine.
