### ISSUE TITLE
Network produces NaN values as output when using geodesic loss as rotation matrices

### ISSUE THREAD

**Issue by duytrangiale** [naver/roma#9]
Hi,

Recently I came up with a weird error when computing the orientation error as the geodesic distance between two rotation matrices rotmat_geodesic_distance(). Whenever I use rotation matrices to calculate the loss function, the model always produce NaN values.

However, when I use unitquat_geodesic_distance(), it works fine. But I'm not sure if this loss is correct or not.

In both cases, the input to the function are two rotation vectors, I then convert it to rotation matrices or unit quaternions depending on the loss I use.

Could you please explain about this error? Thanks for your help.

Cheers,
Duy

**Comment by rbregier** [comment]
Hi,
The expected behavior of this function is described in the documentation:

https://naver.github.io/roma/#roma.utils.rotmat_geodesic_distance

Roughly speaking, it could generate nan if input matrices are "farther than
180 degrees apart" considering the Frobenius norm, depending on the
clamping value. This should not happen if inputs are "true" rotation
matrices, except for numerical precision issues.

Please report a minimal code example if you think you found a bug.

**Comment by duytrangiale** [comment]
Hi,

Thanks for your response. You have mentioned about "true" rotation matrices so I just have a question. My model produces the output as a rotation vector (an arbitrary 3D tensor). I then convert this rotation vector to rotation matrix using roma function rotvec_to_rotmat(). So I just wonder if this rotation matrix is always a "true" rotation matrix?

Do I need any constraint for the output of my model to ensure the output rotation vector is reasonable?

Cheers,
Duy

**Comment by rbregier** [comment]
Conversion should produce a valid rotation matrix yes (up to numerical
precision issues). Could you send a minimal code example that reproduce
your error ?

Regarding your particular use case,  casting to unit quaternions might be
better than casting to rotation matrices as the conversion from rotation
vectors is more straightforward.

Le ven. 15 sept. 2023 à 04:29, Duy (Edward) Le ***@***.***> a
écrit :

**Comment by duytrangiale** [comment]
Hi,

Yes that's true. I can see from your code that the conversion from rotation vector to rotation matrix needs to go through conversion to unit quaternion in the middle so currently I use the quaternions, not matrix. 

I'm just trying a new approach for my model and that needs to use rotation matrices in the loss and I got the error. 

Given two rotation vectors and I convert them to unit quat (or rotation matrix), is there any big difference in terms of calculating geodesic distance between two unit quats (or two rot matrices)?

Thanks

**Comment by rbregier** [comment]
No, there should not be a big difference. If you cannot provide a code
example to reproduce your issue, I will close it.

Le ven. 15 sept. 2023 à 19:51, Duy (Edward) Le ***@***.***> a
écrit :

**Comment by duytrangiale** [comment]
Hi,

Thanks for your response. 

Unfortunately, I cannot create a simple example to replicate this error so I will close this issue now.
